// The Homebrew formula for one release. Pure: `scripts/release.mjs` fills in the version and the tarball's sha256.
// The tarball is expected as an asset of the GitHub release `v<version>` of RELEASES.
export const HOMEPAGE = "https://github.com/adamkchew/grenade-backend";
export const RELEASES = `${HOMEPAGE}/releases/download`;

export function formula({ version, sha256, tarball }) {
  return `# Generated by grenade-backend/scripts/release.mjs. Change packaging/homebrew/formula.mjs, not this file.
# It belongs in the tap as Formula/grenade.rb: brew install adamkchew/grenade/grenade
class Grenade < Formula
  desc "Watch and drive AI coding agents in your Mac's terminals from your phone"
  homepage "${HOMEPAGE}"
  url "${RELEASES}/v${version}/${tarball}"
  sha256 "${sha256}"
  license "MIT"

  depends_on :macos
  depends_on "node"
  depends_on "tmux"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  def caveats
    <<~EOS
      Set Grenade up and pair your phone:
        grenade setup
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grenade --version")
  end
end
`;
}
