# Generated by grenade-cli/scripts/release.mjs. Change packaging/homebrew/formula.mjs, not this file.
# It belongs in the tap as Formula/grenade.rb: brew install holdgrenade/tap/grenade
class Grenade < Formula
  desc "Watch and drive AI coding agents in your Mac's terminals from your phone"
  homepage "https://github.com/holdgrenade/grenade-cli"
  url "https://github.com/holdgrenade/grenade-cli/releases/download/v0.1.1/holdgrenade-cli-0.1.1.tgz"
  sha256 "d0384bb3c4d4d1eb0ad86499d32939eec1543c316dbbde034dbfe40273bb31e1"
  license "MIT"

  depends_on :macos
  depends_on "node"
  depends_on "tmux"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  def caveats
    <<~EOS
      Set Grenade up and pair your phone:
        grenade setup
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/grenade --version")
  end
end
